name: Gravity
version: 1.0.2
main: com.infinityminers.gravity.Gravity

author: jstnf
description: Change gravity in worlds using entity velocity manipulation

commands:
  gravity:
    aliases: [imgravity]
    description: Main command for Gravity.
    permission: gravity.gravity